language: node_js
node_js: node
services: mongodb
install: 
  - yarn
  - yarn setup:client
  - yarn setup:rest-server
  - yarn setup:socket-server
  - yarn setup:coderunner-service
  - cp config/env.sample.js config/env.js
  - yarn env -- development
script:
  - yarn build:client
  - yarn lint
  - yarn start:server &
  - sleep 10
  - yarn test
